export const SET_AUTHENTICATED = "SET_AUTHENTICATED";

// MAP
export const SET_MYMAP = "SET_MYMAP";
export const SET_CURRENT_LAT = "SET_CURRENT_LAT";
export const SET_CURRENT_LNG = "SET_CURRENT_LNG";
export const SET_CURRENT_ZOOM = "SET_CURRENT_ZOOM";
export const GET_MYMAP = "GET_MYMAP";
export const GET_CURRENT_LAT = "GET_CURRENT_LAT";
export const GET_CURRENT_LNG = "GET_CURRENT_LNG";
export const GET_CURRENT_ZOOM = "GET_CURRENT_ZOOM";

// GAME MUTATIONS
export const SET_GAME_STATUS = "SET_GAME_STATUS";
export const SET_ZRR = "SET_ZRR";
export const SET_PLAYER_ID = "SET_PLAYER_ID";
export const SET_PLAYER_POSITION = "SET_PLAYER_POSITION";
export const SET_PLAYER_TTL = "SET_PLAYER_TTL";
export const SET_TTL_CREATION = "SET_TTL_CREATION";
export const SET_CURRENT_TTL = "SET_CURRENT_TTL";
export const SET_PLAYER_ICON = "SET_PLAYER_ICON";
export const SET_METEORITES = "SET_METEORITES";
export const SET_PLAYERS = "SET_PLAYERS";
export const SET_PLAYER_TROPHY = "SET_PLAYER_TROPHY";

export const RESET_STATE = "RESET_STATE";

// GAME GETTERS
export const GET_CURRENT_TTL = "GET_CURRENT_TTL";
